language: python

sudo: false

python:
  - "3.4"

env:
  - WXPYTHON_SNAPSHOTS=https://wxpython.org/Phoenix/snapshot-builds/linux/gtk3/ubuntu-14.04/

notifications:
  email: false

before_install:
  - echo "-----before_install-----"

install:
  - echo "-----install-----"
  # Make sure I'm in the correct directory after all that before_install crap
  - cd /home/travis/build/dougthor42/DiveCalc/

  # Start the install of everything
  - pip install --upgrade pip
  - "pip install --only-binary :all: --pre -f $WXPYTHON_SNAPSHOTS wxPython"
  - pip install -r dev-requirements.txt
  - pip install numpy

script:
  - green pybank -vv --run-coverage

after_success:
  # Send coverage information to coveralls.io
  - coveralls
